### PR TITLE
migrate SmartHome Designer to separate repo

### PR DESCRIPTION
**Pull request by maggu2810**
I added a CHECKLIST.md that should contain a summary what is still to do (and perhaps some more).
But at least it could be build and started.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks. A few questions:

- This will build against the esh-stable p2 repo, is that right? Shouldn't we better make it pull from the nightly repo (so that changes to Xtext DSLs can also be verified on the Designer, before a stable is released)?
- My build is failing with `[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.9.2:compile (default) on project org.eclipse.smarthome.model.item.ui: Error compiling xtend sources in '/Users/kai/Documents/dev/esh/repos/smarthome-designer/bundles/model/org.eclipse.smarthome.model.item.ui/src'. -> [Help 1]` - does it work for you?
- How do you suggest shall we go about the IDE setup? With that move, we now no longer have it included in the Oompf profile of ESH. Shall we add it as an optional repo to checkout? If so, how would we go about the target platform definition (so that the launch configs will continue to work in the IDE)?

**Comment by maggu2810** [comment]
We need to have a look at the build scripts for the p2 repo generation.
As I started the split off it seems that a failed nightly build will result in a non-available or broken nightly p2 repo. But we could check that again.

I started a new build and it succeeded.
I will test a clean checkout and an empty Maven repo again.

As long as the Eclipse IDE supports only one target platform I assume we have to use two different setups.
As long as p2 nightly is part of the target platform the Designer could resolve all its stuff without the need to have the bundles in that IDE.
Not the best solution, but I don't see any change to solve it easily using one IDE and keep the ESH TP clean.

**Comment by maggu2810** [comment]
The file AbstractItemsProposalProvider has been placed in src-gen of model.item.ui after a full build.
But it is not generated by model.item.ui...

Need to check which part generates this file (and perhaps others).

**Comment by maggu2810** [comment]
A build of `org.eclipse.smarthome.model.item` creates
```
./org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/AbstractItemsProposalProvider.java
```

I really don't understand that model stuff.
Why does the build of one artifact generate code in the directory of another one. That sounds a little bit strange.

**Comment by maggu2810** [comment]
I used the current ESH master and removed all model.*.ui directories.
After building the other packages this files has been generates
```text
org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/labeling/ItemsLabelProvider.xtend
org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/labeling/ItemsDescriptionLabelProvider.xtend
org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/outline/ItemsOutlineTreeProvider.xtend
org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/quickfix/ItemsQuickfixProvider.xtend
org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/contentassist/ItemsProposalProvider.xtend
org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/ItemsUiModule.java
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/AbstractItemsProposalProvider.java
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/ItemsParser.java
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalItems.g
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalItemsParser.java
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalItems.tokens
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalItemsLexer.java
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/PartialItemsContentAssistParser.java
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/AbstractItemsUiModule.java
org.eclipse.smarthome.model.item.ui/src-gen/org/eclipse/smarthome/model/ui/ItemsExecutableExtensionFactory.java
org.eclipse.smarthome.model.item.ui/plugin.xml
org.eclipse.smarthome.model.persistence.ui/src/org/eclipse/smarthome/model/persistence/ui/labeling/PersistenceLabelProvider.xtend
org.eclipse.smarthome.model.persistence.ui/src/org/eclipse/smarthome/model/persistence/ui/labeling/PersistenceDescriptionLabelProvider.xtend
org.eclipse.smarthome.model.persistence.ui/src/org/eclipse/smarthome/model/persistence/ui/outline/PersistenceOutlineTreeProvider.xtend
org.eclipse.smarthome.model.persistence.ui/src/org/eclipse/smarthome/model/persistence/ui/quickfix/PersistenceQuickfixProvider.xtend
org.eclipse.smarthome.model.persistence.ui/src/org/eclipse/smarthome/model/persistence/ui/contentassist/PersistenceProposalProvider.xtend
org.eclipse.smarthome.model.persistence.ui/src/org/eclipse/smarthome/model/persistence/ui/PersistenceUiModule.java
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/contentassist/AbstractPersistenceProposalProvider.java
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/contentassist/antlr/PersistenceParser.java
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/contentassist/antlr/internal/InternalPersistence.g
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/contentassist/antlr/internal/InternalPersistenceParser.java
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/contentassist/antlr/internal/InternalPersistence.tokens
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/contentassist/antlr/internal/InternalPersistenceLexer.java
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/contentassist/antlr/PartialPersistenceContentAssistParser.java
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/AbstractPersistenceUiModule.java
org.eclipse.smarthome.model.persistence.ui/src-gen/org/eclipse/smarthome/model/persistence/ui/PersistenceExecutableExtensionFactory.java
org.eclipse.smarthome.model.persistence.ui/plugin.xml
org.eclipse.smarthome.model.rule.ui/src/org/eclipse/smarthome/model/rule/ui/labeling/RulesLabelProvider.xtend
org.eclipse.smarthome.model.rule.ui/src/org/eclipse/smarthome/model/rule/ui/labeling/RulesDescriptionLabelProvider.xtend
org.eclipse.smarthome.model.rule.ui/src/org/eclipse/smarthome/model/rule/ui/outline/RulesOutlineTreeProvider.xtend
org.eclipse.smarthome.model.rule.ui/src/org/eclipse/smarthome/model/rule/ui/quickfix/RulesQuickfixProvider.xtend
org.eclipse.smarthome.model.rule.ui/src/org/eclipse/smarthome/model/rule/ui/contentassist/RulesProposalProvider.xtend
org.eclipse.smarthome.model.rule.ui/src/org/eclipse/smarthome/model/rule/ui/RulesUiModule.java
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/contentassist/AbstractRulesProposalProvider.java
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/contentassist/antlr/RulesParser.java
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/contentassist/antlr/internal/InternalRules.g
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/contentassist/antlr/internal/InternalRulesParser.java
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/contentassist/antlr/internal/InternalRules.tokens
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/contentassist/antlr/internal/InternalRulesLexer.java
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/contentassist/antlr/PartialRulesContentAssistParser.java
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/AbstractRulesUiModule.java
org.eclipse.smarthome.model.rule.ui/src-gen/org/eclipse/smarthome/model/rule/ui/RulesExecutableExtensionFactory.java
org.eclipse.smarthome.model.rule.ui/plugin.xml
org.eclipse.smarthome.model.script.ui/src/org/eclipse/smarthome/model/script/ui/labeling/ScriptLabelProvider.xtend
org.eclipse.smarthome.model.script.ui/src/org/eclipse/smarthome/model/script/ui/labeling/ScriptDescriptionLabelProvider.xtend
org.eclipse.smarthome.model.script.ui/src/org/eclipse/smarthome/model/script/ui/outline/ScriptOutlineTreeProvider.xtend
org.eclipse.smarthome.model.script.ui/src/org/eclipse/smarthome/model/script/ui/quickfix/ScriptQuickfixProvider.xtend
org.eclipse.smarthome.model.script.ui/src/org/eclipse/smarthome/model/script/ui/contentassist/ScriptProposalProvider.xtend
org.eclipse.smarthome.model.script.ui/src/org/eclipse/smarthome/model/script/ui/ScriptUiModule.java
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/contentassist/AbstractScriptProposalProvider.java
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/contentassist/antlr/ScriptParser.java
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/contentassist/antlr/internal/InternalScript.g
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/contentassist/antlr/internal/InternalScriptParser.java
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/contentassist/antlr/internal/InternalScript.tokens
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/contentassist/antlr/internal/InternalScriptLexer.java
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/contentassist/antlr/PartialScriptContentAssistParser.java
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/AbstractScriptUiModule.java
org.eclipse.smarthome.model.script.ui/src-gen/org/eclipse/smarthome/model/script/ui/ScriptExecutableExtensionFactory.java
org.eclipse.smarthome.model.script.ui/plugin.xml
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/labeling/SitemapLabelProvider.xtend
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/labeling/SitemapDescriptionLabelProvider.xtend
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/outline/SitemapOutlineTreeProvider.xtend
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/quickfix/SitemapQuickfixProvider.xtend
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/contentassist/SitemapProposalProvider.xtend
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/SitemapUiModule.java
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/AbstractSitemapProposalProvider.java
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/SitemapParser.java
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalSitemap.g
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalSitemapParser.java
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalSitemap.tokens
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/internal/InternalSitemapLexer.java
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/contentassist/antlr/PartialSitemapContentAssistParser.java
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/AbstractSitemapUiModule.java
org.eclipse.smarthome.model.sitemap.ui/src-gen/org/eclipse/smarthome/model/ui/SitemapExecutableExtensionFactory.java
org.eclipse.smarthome.model.sitemap.ui/plugin.xml
org.eclipse.smarthome.model.thing.ui/src/org/eclipse/smarthome/model/thing/ui/labeling/ThingLabelProvider.xtend
org.eclipse.smarthome.model.thing.ui/src/org/eclipse/smarthome/model/thing/ui/labeling/ThingDescriptionLabelProvider.xtend
org.eclipse.smarthome.model.thing.ui/src/org/eclipse/smarthome/model/thing/ui/outline/ThingOutlineTreeProvider.xtend
org.eclipse.smarthome.model.thing.ui/src/org/eclipse/smarthome/model/thing/ui/quickfix/ThingQuickfixProvider.xtend
org.eclipse.smarthome.model.thing.ui/src/org/eclipse/smarthome/model/thing/ui/contentassist/ThingProposalProvider.xtend
org.eclipse.smarthome.model.thing.ui/src/org/eclipse/smarthome/model/thing/ui/ThingUiModule.java
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/contentassist/AbstractThingProposalProvider.java
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/contentassist/antlr/ThingParser.java
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/contentassist/antlr/internal/InternalThing.g
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/contentassist/antlr/internal/InternalThingParser.java
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/contentassist/antlr/internal/InternalThing.tokens
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/contentassist/antlr/internal/InternalThingLexer.java
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/contentassist/antlr/PartialThingContentAssistParser.java
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/AbstractThingUiModule.java
org.eclipse.smarthome.model.thing.ui/src-gen/org/eclipse/smarthome/model/thing/ui/ThingExecutableExtensionFactory.java
org.eclipse.smarthome.model.thing.ui/plugin.xml
```

**Comment by kaikreuzer** [comment]
> Why does the build of one artifact generate code in the directory of another one. That sounds a little bit strange.

Yes, this is a little strange, but this is how Xtext works. You have the model defined at a single place and from this, you generate the core, the ui and the test code. So I think it will be best to keep the ui bundles in the main repo, there is really no other option.

**Comment by maggu2810** [comment]
The reason I moved the model ui stuff has been because it depends on designer stuff.

**Comment by kaikreuzer** [comment]
You mean Eclipse RCP stuff?

**Comment by maggu2810** [comment]
I mean this one:
```text
org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/contentassist/ItemsProposalProvider.xtend:import org.eclipse.smarthome.designer.ui.UIActivator
org.eclipse.smarthome.model.item.ui/META-INF/MANIFEST.MF: org.eclipse.smarthome.designer.ui,
org.eclipse.smarthome.model.persistence.ui/src/org/eclipse/smarthome/model/persistence/ui/contentassist/PersistenceProposalProvider.xtend:import org.eclipse.smarthome.designer.ui.UIActivator
org.eclipse.smarthome.model.persistence.ui/META-INF/MANIFEST.MF: org.eclipse.smarthome.designer.ui,
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/contentassist/SitemapProposalProvider.xtend:import org.eclipse.smarthome.designer.core.config.ConfigurationFolderProvider
org.eclipse.smarthome.model.sitemap.ui/src/org/eclipse/smarthome/model/ui/contentassist/SitemapProposalProvider.xtend:import org.eclipse.smarthome.designer.ui.UIActivator
org.eclipse.smarthome.model.sitemap.ui/META-INF/MANIFEST.MF: org.eclipse.smarthome.designer.core.config,
org.eclipse.smarthome.model.sitemap.ui/META-INF/MANIFEST.MF: org.eclipse.smarthome.designer.ui,
```

**Comment by kaikreuzer** [comment]
Hm, I will need to have a closer look at the code, if there is some chance to refactor it, so that it can be separated... It won't be too easy, though, I am afraid...

**Comment by maggu2810** [comment]
Perhaps we could keep the model.*.ui bundles in the smarthome repo but the content could be a subset of the current content (e.g. only the generated sources).
The other part of the model.*.ui bundles could be moved to model.*.ui.designer bundles (in this repo) that depends on the stripped down model.*.ui ...
Do you think that could work?

**Comment by maggu2810** [comment]
If you think it could work, I could
* split mode.*.ui to model.*.ui and model.*.ui.designer
* create a feature: org.eclipse.smarthome.feature.runtime.model.ui
* move model.*.ui.designer to designer repo

**Comment by kaikreuzer** [comment]
I cannot promise that it can be split this way, but it sounds like a plan worthwhile to pursue...

**Comment by maggu2810** [comment]
For a first step, I moved only the feature, product and distribution to this repository but kept the bundles itself in the `smarthome` repo.

**Comment by maggu2810** [comment]
@kaikreuzer WDYT? Can we start with this one and start using Java 8 in ESH?

**Comment by kaikreuzer** [comment]
> For a first step, I moved only the feature, product and distribution to this repository but kept the bundles itself in the smarthome repo.

Sounds like a good approach for now.

Sorry for the delay, looks good to me.

**Review by kaikreuzer — APPROVED** [review]

**Pull request merged**
